In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,LabelEncoder

In [2]:
data=pd.read_csv("/content/TONNETZ_MAIN_DATASET.csv")

In [3]:
data.head()

0         1         2         3         4         5  gender  label
0 -0.004285  0.000874 -0.008040 -0.004511  0.008020  0.015510  female  adult
1 -0.036638 -0.008530 -0.017586  0.000417  0.023334 -0.005143  female  adult
2 -0.004850 -0.009209  0.033581 -0.014310  0.001284 -0.006332  female  adult
3  0.013007 -0.021556 -0.008847  0.014096  0.020131  0.000694  female  adult
4  0.020138 -0.033240  0.038399 -0.023844 -0.000725  0.012618  female  adult

In [4]:
data.describe()

0            1            2            3            4  \
count  3000.000000  3000.000000  3000.000000  3000.000000  3000.000000   
mean     -0.000292    -0.001862    -0.000273    -0.004836    -0.000498   
std       0.021933     0.023600     0.037760     0.037722     0.013531   
min      -0.092923    -0.108172    -0.138073    -0.185432    -0.071165   
25%      -0.013841    -0.016465    -0.023219    -0.026753    -0.009595   
50%      -0.001582    -0.001713     0.001390    -0.002001    -0.000574   
75%       0.012628     0.012661     0.022660     0.019105     0.008725   
max       0.140881     0.149102     0.181792     0.130037     0.055538   

                 5  
count  3000.000000  
mean      0.001475  
std       0.012302  
min      -0.070142  
25%      -0.006360  
50%       0.001264  
75%       0.008967  
max       0.062956

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       3000 non-null   float64
 1   1       3000 non-null   float64
 2   2       3000 non-null   float64
 3   3       3000 non-null   float64
 4   4       3000 non-null   float64
 5   5       3000 non-null   float64
 6   gender  3000 non-null   object 
 7   label   3000 non-null   object 
dtypes: float64(6), object(2)
memory usage: 187.6+ KB


In [6]:
data.isnull().sum()

0         0
1         0
2         0
3         0
4         0
5         0
gender    0
label     0
dtype: int64

In [7]:
x=data.iloc[:,:-2]

In [8]:
y=data.iloc[:,-1]

In [9]:
scaler=MinMaxScaler()
x_scaled=scaler.fit_transform(x)
x_scaled[0]

array([0.37911213, 0.42384908, 0.40652365, 0.57349914, 0.62496499,
       0.64352299])

In [10]:
label_encoder=LabelEncoder()
y=label_encoder.fit_transform(y)
y

array([0, 0, 0, ..., 1, 1, 1])

In [11]:
import numpy as np
import random
import tensorflow as tf

# Set random seed for reproducibility
np.random.seed(42)
random.seed(42)
tf.random.set_seed(42)

In [12]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.15, random_state=42)

In [13]:
x_train = np.array(x_train).reshape(-1, 6, 1)
x_test = np.array(x_test).reshape(-1, 6, 1)

In [14]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense,Dropout

In [21]:
# Create a Conv1D model
model = Sequential()
model.add(Conv1D(32, kernel_size=3, activation='relu', input_shape=(6, 1)))
model.add(Dropout(0.2))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))

In [22]:
# Compile and train the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=27, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/27
80/80 [==============================] - 1s 4ms/step - loss: 0.6861 - accuracy: 0.5420 - val_loss: 0.6711 - val_accuracy: 0.6800
Epoch 2/27
80/80 [==============================] - 0s 2ms/step - loss: 0.6627 - accuracy: 0.6322 - val_loss: 0.6466 - val_accuracy: 0.6378
Epoch 3/27
80/80 [==============================] - 0s 2ms/step - loss: 0.6454 - accuracy: 0.6333 - val_loss: 0.6231 - val_accuracy: 0.6822
Epoch 4/27
80/80 [==============================] - 0s 2ms/step - loss: 0.6328 - accuracy: 0.6424 - val_loss: 0.6113 - val_accuracy: 0.6756
Epoch 5/27
80/80 [==============================] - 0s 2ms/step - loss: 0.6308 - accuracy: 0.6424 - val_loss: 0.6023 - val_accuracy: 0.7111
Epoch 6/27
80/80 [==============================] - 0s 2ms/step - loss: 0.6211 - accuracy: 0.6541 - val_loss: 0.5963 - val_accuracy: 0.6933
Epoch 7/27
80/80 [==============================] - 0s 2ms/step - loss: 0.6241 - accuracy: 0.6455 - val_loss: 0.5956 - val_accuracy: 0.6778
Epoch 8/27
80/80 [==

In [23]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense, Dropout, BatchNormalization
from tensorflow.keras.regularizers import l2
from tensorflow.keras.callbacks import EarlyStopping

In [105]:
# Create a Conv1D model
#model = Sequential()
#model.add(Conv1D(32, kernel_size=3, activation='tanh', input_shape=(6, 1)))
#model.add(BatchNormalization())
#model.add(Dropout(0.2))
#model.add(MaxPooling1D(pool_size=2))
#model.add(Dropout(0.2))
#model.add(Flatten())
#model.add(Dense(128, activation='tanh', kernel_regularizer=l2(0.001)))
#model.add(BatchNormalization())
#model.add(Dropout(0.5))
#model.add(Dense(1, activation='softmax'))

In [108]:
from tensorflow.keras.optimizers import RMSprop
optimizer = RMSprop(learning_rate=0.00001)
model.compile(loss='binary_crossentropy', optimizer=optimizer, metrics=['accuracy'])

# Define early stopping callback
early_stop = EarlyStopping(monitor='val_loss', patience=5, restore_best_weights=True)

# Train the model
history = model.fit(x_train, y_train, epochs=2, batch_size=32, validation_data=(x_test, y_test), callbacks=[early_stop])


Epoch 1/2
80/80 [==============================] - 2s 5ms/step - loss: 0.5430 - accuracy: 0.7263 - val_loss: 0.5170 - val_accuracy: 0.7311
Epoch 2/2
80/80 [==============================] - 0s 3ms/step - loss: 0.5395 - accuracy: 0.7373 - val_loss: 0.5175 - val_accuracy: 0.7333


In [109]:
x_scaled[0]

array([0.37911213, 0.42384908, 0.40652365, 0.57349914, 0.62496499,
       0.64352299])

In [110]:
#0

input_sample=[.37911213, 0.42384908, 0.40652365, 0.57349914, 0.62496499,
       0.64352299]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 6, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 98ms/step
[[0]]


In [111]:
#!499
x_scaled[1499]

array([0.34439297, 0.35656666, 0.43755037, 0.51748243, 0.54997412,
       0.59019192])

In [112]:
input_sample=[0.34439297, 0.35656666, 0.43755037, 0.51748243, 0.54997412,
       0.59019192]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 6, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 16ms/step
[[0]]


In [113]:
#1500

x_scaled[1500]


array([0.53707461, 0.64975321, 0.7026934 , 0.74577167, 0.45572837,
       0.76473337])

In [114]:
input_sample=[0.53707461, 0.64975321, 0.7026934 , 0.74577167, 0.45572837,
       0.76473337]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 6, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 18ms/step
[[1]]


In [116]:
#2500
input_sample=[0.53707461, 0.64975321, 0.7026934 , 0.74577167, 0.45572837,
       0.76473337]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 6, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 16ms/step
[[1]]


In [118]:
model.save('1D_CNN_TONNETZ.h5')