In [2]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler,LabelEncoder

In [3]:
data=pd.read_csv("/content/CONTRAST_MAIN_DATASET.csv")

In [4]:
data.head()

0          1          2          3          4          5  \
0  17.608974  12.065717  15.571728  15.820102  16.889392  21.376224   
1  17.873691  10.906630  14.776166  14.746004  16.546733  21.244601   
2  16.731672  11.942405  15.202992  15.605393  16.853212  23.102682   
3  17.411621  12.565404  16.466645  15.366726  17.446967  23.620346   
4  16.476659  11.553081  15.002390  15.148348  18.400752  20.529418   

           6 gender  label  
0  55.152019   male  adult  
1  54.507099   male  adult  
2  54.276696   male  adult  
3  54.526797   male  adult  
4  53.335576   male  adult

In [5]:
data.isnull().sum()

0         0
1         0
2         0
3         0
4         0
5         0
6         0
gender    0
label     0
dtype: int64

In [6]:
data.describe()

0            1            2            3            4  \
count  3000.000000  3000.000000  3000.000000  3000.000000  3000.000000   
mean     15.054482    14.319642    17.827896    18.777976    20.144440   
std       2.813556     1.345302     1.489982     1.993533     1.600574   
min       9.870360     9.559386    11.622897    13.690452    13.998341   
25%      12.494007    13.418963    17.001969    17.201948    19.133750   
50%      15.140901    14.379749    17.906306    18.703296    20.109880   
75%      17.236480    15.268870    18.732714    20.238855    21.197938   
max      24.864515    18.939024    23.216445    27.987939    25.915826   

                 5            6  
count  3000.000000  3000.000000  
mean     23.299326    38.346320  
std       2.274480    12.304000  
min      14.335927    18.563621  
25%      21.843361    26.354443  
50%      23.055719    36.482709  
75%      24.336521    49.380829  
max      35.138256    60.311814

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   0       3000 non-null   float64
 1   1       3000 non-null   float64
 2   2       3000 non-null   float64
 3   3       3000 non-null   float64
 4   4       3000 non-null   float64
 5   5       3000 non-null   float64
 6   6       3000 non-null   float64
 7   gender  3000 non-null   object 
 8   label   3000 non-null   object 
dtypes: float64(7), object(2)
memory usage: 211.1+ KB


In [8]:
x=data.iloc[:,:-2]

In [9]:
y=data.iloc[:,-1]

In [17]:
scaler=MinMaxScaler()
x_scaled=scaler.fit_transform(x)
x_scaled[0]

array([0.51610874, 0.26720983, 0.34060596, 0.14895276, 0.24258903,
       0.33843789, 0.87640675])

In [13]:
label_encoder=LabelEncoder()
y=label_encoder.fit_transform(y)
y

array([0, 0, 0, ..., 1, 1, 1])

In [14]:
import numpy as np
import random
import tensorflow as tf

# Set random seed for reproducibility
np.random.seed(42)
random.seed(42)
tf.random.set_seed(42)

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_scaled, y, test_size=0.15, random_state=42)

In [29]:
x_train = np.array(x_train).reshape(-1, 7, 1)
x_test = np.array(x_test).reshape(-1, 7, 1)

In [30]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, MaxPooling1D, Flatten, Dense,Dropout

In [35]:
# Create a Conv1D model
model = Sequential()
model.add(Conv1D(32, kernel_size=3, activation='tanh', input_shape=(7, 1)))
model.add(Dropout(0.2))
model.add(MaxPooling1D(pool_size=2))
model.add(Dropout(0.2))
model.add(Flatten())
model.add(Dense(128, activation='tanh'))
model.add(Dropout(0.2))
model.add(Dense(1, activation='sigmoid'))

In [37]:
# Compile and train the model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(x_train, y_train, epochs=27, batch_size=32, validation_data=(x_test, y_test))

Epoch 1/27
80/80 [==============================] - 1s 6ms/step - loss: 0.2633 - accuracy: 0.9094 - val_loss: 0.2293 - val_accuracy: 0.9289
Epoch 2/27
80/80 [==============================] - 0s 5ms/step - loss: 0.2546 - accuracy: 0.9106 - val_loss: 0.2260 - val_accuracy: 0.9333
Epoch 3/27
80/80 [==============================] - 0s 5ms/step - loss: 0.2649 - accuracy: 0.9051 - val_loss: 0.2416 - val_accuracy: 0.9067
Epoch 4/27
80/80 [==============================] - 0s 5ms/step - loss: 0.2507 - accuracy: 0.9141 - val_loss: 0.2263 - val_accuracy: 0.9267
Epoch 5/27
80/80 [==============================] - 0s 5ms/step - loss: 0.2386 - accuracy: 0.9212 - val_loss: 0.2224 - val_accuracy: 0.9311
Epoch 6/27
80/80 [==============================] - 0s 5ms/step - loss: 0.2400 - accuracy: 0.9161 - val_loss: 0.2227 - val_accuracy: 0.9289
Epoch 7/27
80/80 [==============================] - 0s 6ms/step - loss: 0.2575 - accuracy: 0.9114 - val_loss: 0.2286 - val_accuracy: 0.9133
Epoch 8/27
80/80 [==

In [38]:
loss, accuracy = model.evaluate(x_test, y_test)
print('Test Loss:', loss)
print('Test Accuracy:', accuracy)

15/15 [==============================] - 0s 3ms/step - loss: 0.2283 - accuracy: 0.9067
Test Loss: 0.22832819819450378
Test Accuracy: 0.9066666960716248


In [40]:
#0

input_sample=[0.51610874, 0.26720983, 0.34060596, 0.14895276, 0.24258903, 0.33843789, 0.87640675]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 7, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)


1/1 [==============================] - 0s 112ms/step
[[0]]


In [41]:
#1499
x_scaled[1499]

array([0.34326221, 0.56890261, 0.58409692, 0.32003246, 0.32146034,
       0.47512885, 0.70391044])

In [42]:
input_sample=[0.34326221, 0.56890261, 0.58409692, 0.32003246, 0.32146034,0.47512885, 0.70391044]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 7, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 25ms/step
[[0]]


In [45]:
x_scaled[1500]

array([0.28494146, 0.77691529, 0.93486349, 0.61852842, 0.72970897,
       0.55838362, 0.16653333])

In [46]:
#1500
input_sample=[0.28494146, 0.77691529, 0.93486349, 0.61852842, 0.72970897,
       0.55838362, 0.16653333]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 7, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 48ms/step
[[1]]


In [50]:
x_scaled[1300]

array([0.66072453, 0.44541321, 0.46179283, 0.15255829, 0.22048902,
       0.19058921, 0.95032366])

In [49]:
#2500
input_sample=[0.2666987 , 0.49128238, 0.55277102, 0.35132052, 0.6995782 ,
       0.43221213, 0.15522193]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 7, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 90ms/step
[[1]]


In [51]:
#1300
input_sample=[0.66072453, 0.44541321, 0.46179283, 0.15255829, 0.22048902,
       0.19058921, 0.95032366]
len(input_sample)
input_sample = np.array(input_sample).reshape(1, 7, 1)
predictions = model.predict(input_sample)
predictions

threshold = 0.5
binary_prediction = (predictions > threshold).astype(int)
print(binary_prediction)

1/1 [==============================] - 0s 35ms/step
[[0]]


In [52]:
model.save('1D_CNN_CONTRAST.h5')